### ISSUE TITLE
[Bug] Citation in markdown does not generate anything than just a padding left

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/rsg-components#3]
Current version of @bootstrap-styled/rsg-components does not handle css for Blockquote 

![image](https://user-images.githubusercontent.com/1866564/49281799-13ed0a00-f4c0-11e8-8192-f69da9f32e27.png)

It only have a padding left.

I would expect for a citation, to have a different layout such as:

- Surrounding blockquote.
- Background (such as alert info).
- Giving informative sensation.

This ticket consist of adding default styles to blockquote.

They can be identified in markdown with: 

```md
> This is a blockquote
```

**Comment by santaclauze** [comment]
So, styling is actually applied correctly. The issue is that because we use @bootstrap-styled/v4 components. Some of the css rules were clashing between both libraries.

I removed the overriding rules of variables in rsg-components/Markdown/Blockquote in favour for those of @bs/v4.

https://github.com/bootstrap-styled/rsg-components/pull/5
